INSERT INTO 
    music(artist, track, album, playlist)
VALUES
('Breaking Benjamin','The Diary of Jane - Single Version','Phobia (Clean Version)','workout'), 
('Trapt','Headstrong','Trapt','workout'), 
('Ariana Grande','thank u next','thank u, next','workout'), 
('Theory of a Deadman','Rx (Medicate)','Wake Up Call','workout'), 
('Kodak Black','ZEZE (feat. Travis Scott & Offset)','ZEZE (feat. Travis Scott & Offset)','workout'), 
('Eminem','Till I Collapse','The Eminem Show','workout'), 
('Kanye West','Mercy','Mercy','workout'), 
('Jason Derulo','Swalla (feat. Nicki Minaj & Ty Dolla $ign)','Swalla (feat. Nicki Minaj & Ty Dolla $ign)','workout'), 
('David Guetta','Where Them Girls At (feat. Nicki Minaj & Flo Rida)','Nothing but the Beat 2.0','workout'), 
('Heart','Barracuda','Little Queen','workout'), 
('J. Cole','Power Trip (feat. Miguel)','Born Sinner','workout'), 
('Eminem','Fall','Kamikaze','workout'), 
('Mötley Crüe','Kickstart My Heart','Dr. Feelgood','workout'), 
('Machine Gun Kelly','Bad Mother F*cker','General Admission','workout'), 
('Jason Aldean','Girl Like You','Rearview Town','workout'), 
('Quiet Riot','Cum on Feel the Noize','Quiet Riot - Greatest Hits','workout'), 
('Def Leppard','Pour Some Sugar On Me - Remastered 2017','Hysteria (Super Deluxe)','workout'), 
('Def Leppard','Animal','Hysteria','workout'), 
('Def Leppard','Rock Of Ages','Pyromania (Deluxe)','workout'), 
('Def Leppard','Hysteria','Hysteria','workout'), 
('Def Leppard','Love Bites - Remastered 2017','Hysteria (Super Deluxe)','workout'), 
('Van Halen','Aint Talkin Bout Love - 2015 Remaster','Van Halen (Remastered)','workout'), 
('AC/DC','Back In Black','Back In Black','workout'), 
('Journey','Separate Ways (Worlds Apart)','Frontiers','workout'), 
('Sum 41','In Too Deep','All Killer, No Filler','workout'), 
('Sum 41','Fat Lip','All Killer, No Filler','workout'), 
('Ratt','Round and Round','Out Of The Cellar','workout'), 
('Warrant','Cherry Pie','Cherry Pie (Expanded Edition)','workout'), 
('Bon Jovi','You Give Love A Bad Name','Slippery When Wet','workout'), 
('Logic','1-800-273-8255','Everybody','workout'), 
('blink-182','I Miss You','blink-182','workout'), 
('blink-182','Feeling This','blink-182','workout'), 
('blink-182','First Date','Take Off Your Pants And Jacket','workout'), 
('Post Malone','Sunflower - Spider-Man: Into the Spider-Verse','Sunflower (Spider-Man: Into the Spider-Verse)','workout'), 
('G-Eazy','Him & I (with Halsey)','The Beautiful & Damned','workout'), 
('Halsey','Without Me','Without Me','workout'), 
('Maroon 5','Girls Like You (feat. Cardi B) - Cardi B Version','Red Pill Blues (Deluxe)','workout'), 
('Khalid','Better','Suncity','workout'), 
('N.W.A.','Straight Outta Compton','Straight Outta Compton','workout'), 
('Post Malone','Sunflower - Spider-Man: Into the Spider-Verse','Sunflower (Spider-Man: Into the Spider-Verse)','workout'), 
('Styx','Renegade','Pieces Of Eight','workout'), 
('Black Eyed Peas','I Gotta Feeling','THE E.N.D. (THE ENERGY NEVER DIES)','workout'), 
('Kane Brown','What Ifs (feat. Lauren Alaina)','Kane Brown','workout'), 
('2 Chainz','Boo','Codeine Cowboy ( A 2 Chainz Collective)','workout'), 
('Ava Max','Sweet but Psycho','Sweet but Psycho','workout'), 
('Fall Out Boy','Centuries','American Beauty/American Psycho','workout'), 
('Fall Out Boy','Thnks fr th Mmrs','Infinity On High','workout'), 
('Fall Out Boy','This Aint A Scene, Its An Arms Race','Infinity On High','workout'), 
('Panic! At The Disco','I Write Sins Not Tragedies','A Fever You Cant Sweat Out','workout'), 
('LP','Muddy Waters','Lost on You','workout'), 
('Daniel Spaleniak','Dear love of mine','Back Home','workout'), 
('Rob Thomas','This Is How a Heart Breaks','Something to Be','workout'), 
('Skid Row','Youth Gone Wild','Skid Row','workout'), 
('Def Leppard','Let It Go','High N Dry','workout'), 
('Skid Row','18 and Life','Skid Row','workout'), 
('The Red Jumpsuit Apparatus','Face Down','Dont You Fake It','workout'), 
('The Script','For the First Time','Science & Faith','workout'), 
('Billy Squier','Everybody Wants You - Remastered 2002','Absolute Hits','workout'), 
('French Montana','Unforgettable','Jungle Rules','workout'), 
('Harvey Danger','Flagpole Sitta','Where Have All The Merrymakers Gone?','workout'), 
('Rush','Tom Sawyer','Moving Pictures (2011 Remaster)','workout'), 
('Florida Georgia Line','Im In A Hurry (And Dont Know Why)','Alabama & Friends','workout'), 
('Florida Georgia Line','This Is How We Roll - Remix','This Is How We Roll (Remix)','workout'), 
('Lou Bega','Mambo No. 5 (a Little Bit of...)','A Little Bit of Mambo','workout'), 
('5 Seconds of Summer','Easier','Easier','workout'), 
('Old Dominion','Song for Another Time','Meat and Candy','workout'), 
('Billy Currington','Hey Girl','We Are Tonight','workout'), 
('Halsey','Bad At Love','hopeless fountain kingdom (Deluxe)','workout'), 
('MC Hammer','U Cant Touch This','Please Hammer Dont Hurt Em','workout'), 
('Scouting For Girls','This Aint a Love Song - Radio Edit','This Aint a Love Song (Radio Edit)','workout'), 
('Eddie Money','Shakin','No Control','workout'), 
('Thirty Seconds To Mars','The Kill','A Beautiful Lie','workout'), 
('Ted Nugent','Stranglehold','Ted Nugent','workout'), 
('Default','Wasting My Time','The Fallout (Limited Edition)','workout'), 
('Kelly Rowland','Motivation','Motivation','workout'), 
('Waka Flocka Flame','No Hands (feat. Roscoe Dash & Wale)','Flockaveli','workout'), 
('B.o.B','We Still in this Bitch (feat. T.I. and Juicy J)','Underground Luxury','workout'), 
('Brantley Gilbert','Bottoms Up - Remix','Just As I Am (Platinum Edition)','workout'), 
('Shawn Mendes','If I Cant Have You','If I Cant Have You','workout'), 
('Lil Baby','Yes Indeed','Harder Than Ever','workout'), 
('Dean Lewis','Be Alright','Be Alright','workout'), 
('Lifehouse','Between The Raindrops','Almeria (Deluxe)','workout'), 
('Lifehouse','Halfway Gone','Smoke & Mirrors (Deluxe)','workout'), 
('The Offspring','Pretty Fly (For A White Guy)','Americana','workout'), 
('Rae Sremmurd','Powerglide (feat. Juicy J) - From SR3MM','SR3MM','workout'), 
('Kanye West','Heartless','808s & Heartbreak','workout'), 
('Demi Lovato','Heart Attack','Demi','workout'), 
('Taylor Swift','Bad Blood','Bad Blood','workout'), 
('Kool & The Gang','Get Down On It - Single Version','The Very Best Of Kool & The Gang (Reissue)','workout'), 
('Halsey','Graveyard','Graveyard','workout'), 
('Five For Fighting','Chances','Slice','workout'), 
('Rob Thomas','Little Wonders','Little Wonders','workout'), 
('Chris Webby','Left Lane','Homegrown','workout'), 
('Selena Gomez','Back To You','13 Reasons Why (Season 2)','workout'), 
('Miley Cyrus','We Cant Stop','Bangerz (Deluxe Version)','workout'), 
('Miley Cyrus','Do My Thang','Bangerz (Deluxe Version)','workout'), 
('Ciara','Goodies (feat. Petey Pablo)','Goodies','workout'), 
('Tech N9ne','I Caught Crazy! (4Ever)','N9NA','workout'), 
('Mac Miller','Loud','Loud','workout'), 
('Cardi B','I Like It','Invasion of Privacy','workout'), 
('LOCASH','I Know Somebody','The Fighters','workout'), 
('Eminem','W.T.P.','Recovery','workout'), 
('Tech N9ne','Like Yeah','Killer','workout'), 
('Christina Aguilera','Fighter','Stripped','workout'), 
('The Weeknd','Heartless','After Hours','workout'), 
('Imagine Dragons','Whatever It Takes','Evolve','workout'), 
('P!nk','Stupid Girls','Im Not Dead','workout'), 
('P!nk','U + Ur Hand','Im Not Dead','workout'), 
('Nelly Furtado','Maneater','Loose','workout'), 
('Cardi B','Bodak Yellow','Invasion of Privacy','workout'), 
('DJ Khaled','Wish Wish (feat. Cardi B & 21 Savage)','Father Of Asahd','workout'), 
('Jason Aldean','Take A Little Ride','Night Train','workout'), 
('Britney Spears','Work Bitch','Britney Jean (Deluxe Version)','workout'), 
('Post Malone','rockstar (feat. 21 Savage)','beerbongs & bentleys','workout'), 
('Daughtry','Over You','Daughtry (Deluxe Edition)','workout'), 
('Daughtry','Its Not Over','Daughtry (Deluxe Edition)','workout'), 
('Daughtry','Home','Daughtry (Deluxe Edition)','workout'), 
('Tech N9ne','Caribou Lou','Everready','workout'), 
('Theory of a Deadman','Not Meant to Be','Scars & Souvenirs (Special Edition)','workout'), 
('Theory of a Deadman','All or Nothing','Scars & Souvenirs (Special Edition)','workout'), 
('Gavin DeGraw','In Love With a Girl','Gavin DeGraw','workout'), 
('REO Speedwagon','Roll with the Changes','You Can Tune a Piano, But You Cant Tuna Fish','workout'), 
('Good Charlotte','The Anthem','The Young and The Hopeless','workout'), 
('The Interrupters','Shes Kerosene','Fight the Good Fight','workout'), 
('D12','My Band','D-12 World','workout'), 
('The Weeknd','Blinding Lights','After Hours','workout'), 
('KYLE','iSpy (feat. Lil Yachty)','iSpy (feat. Lil Yachty)','workout'), 
('Eagles','Life in the Fast Lane - 2013 Remaster','Hotel California (2013 Remaster)','workout'), 
('Michael Bublé','Havent Met You Yet','Crazy Love','workout'), 
('Michael Bublé','Home','Its Time','workout'), 
('Jason Aldean','Burnin It Down','Old Boots, New Dirt','workout'), 
('Pitbull','International Love (feat. Chris Brown)','Planet Pit (Deluxe Version)','workout'), 
('Zedd','Stay','Stay','workout'), 
('The Fray','Heartbeat','Scars & Stories','workout'), 
('Roddy Ricch','The Box','Please Excuse Me for Being Antisocial','workout'), 
('Eminem','Deja Vu','Relapse: Refill','workout'), 
('3OH!3','My First Kiss (feat. Ke$ha)','Streets Of Gold','workout'), 
('Wiz Khalifa','See You Again (feat. Charlie Puth)','See You Again (feat. Charlie Puth)','workout'), 
('Lizzo','Good as Hell (feat. Ariana Grande) - Remix','Good as Hell (feat. Ariana Grande) [Remix]','workout'), 
('Michael Bublé','Its a Beautiful Day','To Be Loved','workout'), 
('Lil Wayne','Mr. Carter','Tha Carter III','workout'), 
('Jake Owen','American Country Love Song','American Love','workout'), 
('The Chainsmokers','Paris','Paris','workout'), 
('Mary J. Blige','Family Affair','No More Drama','workout'), 
('Kreayshawn','Left Ey3','Somethin Bout Kreay','workout'), 
('Eminem','You Gon’ Learn','Music To Be Murdered By','workout'), 
('Ellie Goulding','Love Me Like You Do','Fifty Shades Freed (Original Motion Picture Soundtrack)','workout'), 
('AJR','Bang!','Bang!','workout'), 
('Avicii','Hey Brother','TRUE','workout'), 
('We The Kings','Check Yes, Juliet','We The Kings','workout'), 
('B.o.B','HeadBand (feat. 2 Chainz)','Underground Luxury','workout'), 
('Boys Like Girls','Love Drunk','Love Drunk','workout'), 
('Third Eye Blind','Semi-Charmed Life','Third Eye Blind','workout'), 
('The Offspring','The Kids Arent Alright','Americana','workout'), 
('Gym Class Heroes','Cupids Chokehold / Breakfast in America','The Papercut Chronicles','workout'), 
('Tech N9ne','Imma Tell','Absolute Power','workout'), 
('DJ Khaled','All I Do Is Win','Victory','workout'), 
('Machine Gun Kelly','bloody valentine','Tickets To My Downfall','workout'), 
('The Goo Goo Dolls','Slide','Dizzy up the Girl','workout'), 
('Demi Lovato','Sorry Not Sorry','Tell Me You Love Me (Deluxe)','workout'), 
('Matchbox Twenty','Unwell','More Than You Think You Are','workout'), 
('Barenaked Ladies','Odds Are','Grinning Streak','workout'), 
('Aerosmith','Dream On','Aerosmith','workout'), 
('Mariah Carey','Obsessed','Memoirs of an imperfect Angel','workout'), 
('Eminem','Farewell','Music To Be Murdered By','workout'), 
('Justin Bieber','Hold On','Justice','workout'), 
('The Chainsmokers','Takeaway','World War Joy','workout'), 
('Saweetie','Best Friend (feat. Doja Cat)','Best Friend (feat. Doja Cat)','workout'), 
('Fifth Harmony','Work from Home (feat. Ty Dolla $ign)','7/27 (Deluxe)','workout'), 
('Pia Mia','Do It Again','Do It Again','workout'), 
('Chris Webby','Keep Rollin (feat. Bennett)','Next Wednesday','workout'), 
('Cardi B','I Like It','Invasion of Privacy','workout'), 
('The Darkness','I Believe in a Thing Called Love','Permission to Land','workout'), 
('Kris Allen','Live Like Were Dying','Kris Allen','workout'), 
('Elton John','Rocket Man','Honky Chateau','workout'), 
('Elton John','Im Still Standing','Too Low For Zero','workout'), 
('Everclear','Father Of Mine','So Much For The Afterglow','workout'), 
('Adam Lambert','Whataya Want from Me','For Your Entertainment','workout'), 
('Tyga','Taste (feat. Offset)','Taste (feat. Offset)','workout'), 
('Saweetie','Best Friend (feat. Doja Cat)','Best Friend (feat. Doja Cat)','workout'), 
('The Chainsmokers','Closer','Closer','workout'), 
('The Chainsmokers','Call You Mine','World War Joy','workout'), 
('Masked Wolf','Astronaut In The Ocean','Astronaut In The Ocean','workout'), 
('blackbear','hot girl bummer','everything means nothing','workout'), 
('Anna Nalick','Breathe (2 AM)','Wreck of the Day','workout'), 
('Limp Bizkit','Rollin','Chocolate Starfish And The Hot Dog Flavored Water','workout'), 
('Limp Bizkit','My Way','Chocolate Starfish And The Hot Dog Flavored Water','workout'), 
('Gavin DeGraw','I Dont Want to Be','Chariot','workout'), 
('Third Eye Blind','Jumper - 1998 Edit','Third Eye Blind','workout'), 
('Fall Out Boy','Uma Thurman','American Beauty/American Psycho','workout'), 
('Pitbull','Timber (feat. Ke$ha)','Global Warming: Meltdown (Deluxe Version)','workout'), 
('Fifth Harmony','All In My Head (Flex) (feat. Fetty Wap)','7/27 (Deluxe)','workout'), 
('X Ambassadors','Renegades','VHS','workout'), 
('Fetty Wap','679 (feat. Remy Boyz)','679 (feat. Remy Boyz)','workout'), 
('The Kid LAROI','STAY (with Justin Bieber)','F*CK LOVE 3: OVER YOU','workout')
RETURNING *;