INSERT INTO 
    music(record_number,artist, track, album, playlist)
VALUES
(1,'Breaking Benjamin','The Diary of Jane - Single Version','Phobia (Clean Version)','workout'), 
(2,'Trapt','Headstrong','Trapt','workout'), 
(3,'Ariana Grande','thank u next','thank u, next','workout'), 
(4,'Theory of a Deadman','Rx (Medicate)','Wake Up Call','workout'), 
(5,'Kodak Black','ZEZE (feat. Travis Scott & Offset)','ZEZE (feat. Travis Scott & Offset)','workout'), 
(6,'Eminem','Till I Collapse','The Eminem Show','workout'), 
(7,'Kanye West','Mercy','Mercy','workout'), 
(8,'Jason Derulo','Swalla (feat. Nicki Minaj & Ty Dolla $ign)','Swalla (feat. Nicki Minaj & Ty Dolla $ign)','workout'), 
(9,'David Guetta','Where Them Girls At (feat. Nicki Minaj & Flo Rida)','Nothing but the Beat 2.0','workout'), 
(10,'Heart','Barracuda','Little Queen','workout'), 
(11,'J. Cole','Power Trip (feat. Miguel)','Born Sinner','workout'), 
(12,'Eminem','Fall','Kamikaze','workout'), 
(13,'Mötley Crüe','Kickstart My Heart','Dr. Feelgood','workout'), 
(14,'Machine Gun Kelly','Bad Mother F*cker','General Admission','workout'), 
(15,'Jason Aldean','Girl Like You','Rearview Town','workout'), 
(16,'Quiet Riot','Cum on Feel the Noize','Quiet Riot - Greatest Hits','workout'), 
(17,'Def Leppard','Pour Some Sugar On Me - Remastered 2017','Hysteria (Super Deluxe)','workout'), 
(18,'Def Leppard','Animal','Hysteria','workout'), 
(19,'Def Leppard','Rock Of Ages','Pyromania (Deluxe)','workout'), 
(20,'Def Leppard','Hysteria','Hysteria','workout'), 
(21,'Def Leppard','Love Bites - Remastered 2017','Hysteria (Super Deluxe)','workout'), 
(22,'Van Halen','Aint Talkin Bout Love - 2015 Remaster','Van Halen (Remastered)','workout'), 
(23,'AC/DC','Back In Black','Back In Black','workout'), 
(24,'Journey','Separate Ways (Worlds Apart)','Frontiers','workout'), 
(25,'Sum 41','In Too Deep','All Killer, No Filler','workout'), 
(26,'Sum 41','Fat Lip','All Killer, No Filler','workout'), 
(27,'Ratt','Round and Round','Out Of The Cellar','workout'), 
(28,'Warrant','Cherry Pie','Cherry Pie (Expanded Edition)','workout'), 
(29,'Bon Jovi','You Give Love A Bad Name','Slippery When Wet','workout'), 
(30,'Logic','1-800-273-8255','Everybody','workout')
RETURNING *;